import { GUARD_SCRIPT } from "./hook-document.js";

/**
 * The edit guard `agent install` writes: a POSIX `sh` script with the
 * destination's generated files baked in.
 *
 * It exists because the hook it replaces started two Node processes on every
 * edit in every repository -- the hook, and a `cairn agent guard` child whose
 * fixed startup was the whole cost -- and that, multiplied across parallel
 * agents, pinned machines. This script forks nothing on the allow path. The
 * decision is a `case` over exact paths, and the paths are the install
 * inventory: what `cairn agent install` wrote, not what an output pattern could
 * describe. So there is no pattern matching at run time and no oracle to keep
 * in step, only a list that the next install rewrites.
 *
 * Everything in the output is derived from the inventory and the `agent.guard`
 * block. No timestamp, no argv, no absolute path -- `agent verify` regenerates
 * the script from the manifest and must get the same bytes, and a moved or
 * symlinked checkout must keep working, so the script finds its own root from
 * `$0`.
 *
 * Portability rules, because CI's `/bin/sh` is dash and macOS's is bash in
 * POSIX mode: no `local`, arrays, `[[`, `${var//}`, `$'...'`, `grep -P`,
 * `readlink -f`, or `timeout`; no backslashes in awk *replacement* strings,
 * which the implementations disagree about; and `[ \t\r\n]` rather than POSIX
 * character classes, which older mawk lacked.
 */

/** One generated file, destination-relative, with what produces it. */
export interface GuardScriptEntry {
  path: string;
  /** The owning bundle's name, or `undefined` when several bundles merge into the file. */
  bundle?: string;
  /** Destination-relative bundle files to edit instead; empty when unknown. */
  sources: string[];
}

export interface GuardScriptInput {
  mode: "block" | "warn";
  /** Destination-relative paths the guard never claims; a trailing `/**` covers a directory. */
  allow: string[];
  /** The command quoted back to the editor. */
  regenerate: string;
  entries: GuardScriptEntry[];
}

/** A value that cannot be spelled inside single quotes without changing meaning. */
export function hasControlCharacters(value: string): boolean {
  // eslint-disable-next-line no-control-regex
  return /[\u0000-\u001f\u007f]/.test(value);
}

/** Single-quoted for `sh`: the only escape needed is the quote itself. */
function quote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

/** Byte comparison, never `localeCompare`: these bytes are generated output. */
function byBytes(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

function allowPattern(pattern: string): string {
  if (!pattern.endsWith("/**")) return quote(pattern);
  const prefix = pattern.slice(0, -3);
  return `${quote(prefix)}|${quote(`${prefix}/`)}*`;
}

/**
 * Renders the script. Entries are sorted by byte comparison of path; the
 * caller has already dropped any path {@link hasControlCharacters} rejects.
 */
export function renderGuardScript(input: GuardScriptInput): Buffer {
  const entries = [...input.entries].sort((a, b) => byBytes(a.path, b.path));
  const lead =
    input.mode === "block"
      ? "Refusing to edit a cairn-generated file."
      : "Editing a cairn-generated file; the next render will overwrite it.";

  const branches = entries.map((entry) => {
    const lines = [`${quote(entry.path)})`];
    if (entry.bundle) lines.push(`  bundle=${quote(entry.bundle)}`);
    if (entry.sources.length)
      lines.push(`  sources=${quote([...entry.sources].sort(byBytes).join("\n"))}`);
    lines.push("  ;;");
    return lines.join("\n");
  });

  const allow = input.allow.length
    ? [
        "# Paths agent.guard.allow hands back to the editor.",
        "case $rel in",
        ...input.allow.map((pattern) => `  ${allowPattern(pattern)}) exit 0 ;;`),
        "esac",
        "",
      ]
    : [];

  const script = [
    "#!/bin/sh",
    "# Generated by `cairn agent install`; do not edit. Regenerate with:",
    `#   ${input.regenerate}`,
    "#",
    "# PreToolUse edit guard for this repository. It refuses an edit to a file",
    "# cairn generated here and names the bundle source to edit instead. The list",
    "# below is the install inventory: exactly what `cairn agent install` wrote,",
    "# nothing matched by pattern. Every failure of the script's own exits 0 -- a",
    "# guard that failed closed would block every edit -- and only a decided",
    "# refusal exits 2.",
    "",
    `mode=${input.mode}`,
    `regenerate=${quote(input.regenerate)}`,
    "",
    "# The destination is wherever this script lives, canonically, so a moved or",
    "# symlinked checkout keeps working and nothing absolute is baked in.",
    'root=$(CDPATH= cd -- "$(dirname -- "$0")" 2>/dev/null && pwd -P) || exit 0',
    '[ -n "$root" ] || exit 0',
    "",
    "# The host's event, bounded: one larger than this is not one a host wrote.",
    "event=$(head -c 1048576 2>/dev/null) || exit 0",
    '[ -n "$event" ] || exit 0',
    "",
    "# The first string value under any of the given keys, keys in order of",
    "# preference, or nothing. Content strings are JSON-escaped, so a",
    '# `\\"file_path\\"` inside a Write body cannot match a bare-quoted key. A value',
    "# carrying an escape is reported as nothing: decoding JSON in sh is where a",
    "# guard starts getting things wrong, and nothing means allow.",
    "json_string() {",
    '  printf \'%s\\n\' "$event" | awk -v keys="$1" \'',
    '    { text = text $0 "\\n" }',
    "    END {",
    '      n = split(keys, key, " ")',
    "      for (i = 1; i <= n; i++) {",
    '        if (match(text, "\\"" key[i] "\\"[ \\t\\r\\n]*:[ \\t\\r\\n]*\\"[^\\"]*\\"")) {',
    "          s = substr(text, RSTART, RLENGTH)",
    '          sub(/^"[^"]*"[ \\t\\r\\n]*:[ \\t\\r\\n]*"/, "", s)',
    '          sub(/"$/, "", s)',
    '          if (index(s, "\\\\") == 0) print s',
    "          exit",
    "        }",
    "      }",
    "    }'",
    "}",
    "",
    "# Filtered here as well as by the matcher: Cursor's handler shape drops the",
    "# matcher, and without this the guard would ask about every command it runs.",
    'tool=$(json_string "tool_name toolName tool")',
    "case $tool in",
    "  ''|Edit|Write|MultiEdit|NotebookEdit|apply_patch|edit_file|write_file|create_file|search_replace) ;;",
    "  *) exit 0 ;;",
    "esac",
    "",
    'file=$(json_string "file_path filePath notebook_path notebookPath path file")',
    '[ -n "$file" ] || exit 0',
    "case $file in /*) ;; *) file=$PWD/$file ;; esac",
    "",
    "# Canonical through the nearest existing ancestor, so a path through a symlink",
    "# agrees with $root and a Write into a directory that does not exist yet still",
    "# resolves.",
    "canonical() {",
    "  p=$1",
    "  tail=",
    '  while [ ! -d "$p" ]; do',
    '    tail=$(basename -- "$p")${tail:+/$tail}',
    '    q=$(dirname -- "$p")',
    '    [ "$q" = "$p" ] && break',
    "    p=$q",
    "  done",
    '  p=$(CDPATH= cd -- "$p" 2>/dev/null && pwd -P) || return 1',
    "  printf '%s\\n' \"${p%/}${tail:+/$tail}\"",
    "}",
    'abs=$(canonical "$file") || exit 0',
    "",
    "case $abs in",
    '  "$root"/*) rel=${abs#"$root"/} ;;',
    "  *) exit 0 ;;",
    "esac",
    "",
    ...allow,
    "# The install inventory. Each branch names the bundle that produced the file",
    "# and the bundle files to edit instead, newline-separated.",
    "bundle=",
    "sources=",
    "case $rel in",
    ...branches,
    "*) exit 0 ;;",
    "esac",
    "",
    "nl='",
    "'",
    "from=",
    '[ -n "$bundle" ] && from=" from bundle \'$bundle\'"',
    `msg="${lead}`,
    "",
    "  $rel",
    '  is generated by cairn$from."',
    'if [ -n "$sources" ]; then',
    "  case $sources in",
    '    *"$nl"*) msg="$msg${nl}${nl}Edit the source instead, in:" ;;',
    '    *) msg="$msg${nl}${nl}Edit the source instead:" ;;',
    "  esac",
    "  msg=\"$msg$nl$(printf '%s\\n' \"$sources\" | sed 's/^/  /')\"",
    "else",
    '  msg="$msg${nl}${nl}It is regenerated by every install; edit the bundle or the cairn configuration instead."',
    "fi",
    'msg="$msg${nl}${nl}Then regenerate:${nl}  $regenerate"',
    "",
    "# Claude Code and Codex block on exit 2 with the reason on stderr; Cursor",
    "# reads a JSON decision on stdout and ignores the status. Cursor's event has",
    "# no hook_event_name.",
    "case $event in",
    "  *'\"hook_event_name\"'*) host=stderr ;;",
    "  *'\"conversation_id\"'*|*'\"workspace_roots\"'*) host=cursor ;;",
    "  *) host=stderr ;;",
    "esac",
    "",
    'if [ "$host" = cursor ]; then',
    "  # JSON-escape with sed, and join lines with awk printing a literal backslash-n;",
    "  # awk's own gsub replacement is where backslash handling diverges.",
    '  json=$(printf \'%s\\n\' "$msg" | sed \'s/\\\\/\\\\\\\\/g; s/"/\\\\"/g; s/\t/\\\\t/g\' | awk \'NR > 1 { printf "\\\\n" } { printf "%s", $0 }\')',
    '  if [ "$mode" = block ]; then permission=deny; else permission=allow; fi',
    '  printf \'{"permission":"%s","agentMessage":"%s","userMessage":"%s"}\\n\' "$permission" "$json" "$json"',
    "  exit 0",
    "fi",
    "",
    "printf '%s\\n' \"$msg\" >&2",
    '[ "$mode" = block ] && exit 2',
    "exit 0",
    "",
  ];
  return Buffer.from(script.join("\n"));
}

export { GUARD_SCRIPT };
