import type { CompletionCommand, CompletionModel, Shell } from "./model.js";

/**
 * Shell script generators.
 *
 * Every script is *static*: it embeds the command tree rather than calling back
 * into the CLI. A callback would spawn a Node process on every Tab press, and
 * would need a hidden command — CLI surface that behaves like an API but is
 * excluded from `describe` by construction. Nothing here is dynamic, so there
 * is nothing to gain in exchange.
 */

/** Escapes for a single-quoted POSIX shell string. */
function sq(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/** Escapes for a double-quoted PowerShell string. */
function ps(value: string): string {
  return `"${value.replace(/`/g, "``").replace(/"/g, '`"').replace(/\$/g, "`$")}"`;
}

/** Escapes a zsh `_describe`/`_arguments` description, which is `:`-delimited. */
function zshDescription(value: string): string {
  return value.replace(/([:\\[\]])/g, "\\$1");
}

/** A single line, so a description can never break a generated line. */
function oneLine(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

function header(model: CompletionModel, comment: string): string {
  return [
    `${comment} ${model.binary} shell completion`,
    `${comment} Generated by ${model.binary} ${model.version}. Regenerate after upgrading.`,
    `${comment} Do not edit.`,
  ].join("\n");
}

/** Flags a shell should offer for a command, longs and shorts, sorted. */
function flags(command: CompletionCommand): string[] {
  return command.options
    .flatMap((option) => (option.short ? [option.short, option.long] : [option.long]))
    .sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
}

/** Words a shell should offer for a command's own position. */
function words(command: CompletionCommand): string[] {
  const subcommands = command.subcommands.map((id) => id.split(" ").pop()!);
  return [...subcommands, ...command.argument.choices, ...flags(command)];
}

/** Options that take a value, with what to offer after them. */
function valueOptions(command: CompletionCommand): CompletionCommand["options"] {
  return command.options.filter((option) => option.takesValue);
}

function bash(model: CompletionModel): string {
  // Derived rather than written out, because the two sites below are the only
  // places in this file the binary name does not already reach through
  // `model.binary` — the reason they still said CLAUDE_CLI long after the tool
  // was named something else.
  const pathsVariable = `_${model.binary.toUpperCase().replace(/[^A-Z0-9_]/g, "_")}_PATHS`;
  const lines = [
    header(model, "#"),
    "",
    `_${model.binary.replace(/-/g, "_")}_completions() {`,
    "  local cur prev command_path index word",
    '  cur="${COMP_WORDS[COMP_CWORD]}"',
    '  prev="${COMP_WORDS[COMP_CWORD-1]}"',
    "",
    "  # Longest known command path formed by the leading non-flag words.",
    '  command_path=""',
    "  index=1",
    '  while [ "$index" -lt "$COMP_CWORD" ]; do',
    '    word="${COMP_WORDS[$index]}"',
    '    case "$word" in -*) break ;; esac',
    `    case " \${${pathsVariable}} " in`,
    '      *" ${command_path:+$command_path }$word "*) command_path="${command_path:+$command_path }$word" ;;',
    "      *) break ;;",
    "    esac",
    "    index=$((index + 1))",
    "  done",
    "",
    "  # A value position: offer the option's own vocabulary, not the command's.",
    '  case "$command_path|$prev" in',
  ];
  for (const command of model.commands)
    for (const option of valueOptions(command)) {
      const pattern = `${command.id}|${option.long}`;
      const alias = option.short ? `${command.id}|${option.short}` : null;
      const match = alias ? `${sq(pattern)} | ${sq(alias)}` : sq(pattern);
      if (option.value === "choice")
        lines.push(
          `    ${match}) COMPREPLY=($(compgen -W ${sq(option.choices.join(" "))} -- "$cur")); return ;;`,
        );
      // file, directory, and free all defer to `-o default`, which is bash's
      // own path completion and beats anything embedded here.
      else lines.push(`    ${match}) COMPREPLY=(); return ;;`);
    }
  lines.push(
    "  esac",
    "",
    '  case "$command_path" in',
    ...model.commands.map(
      (command) =>
        `    ${sq(command.id)}) COMPREPLY=($(compgen -W ${sq(words(command).join(" "))} -- "$cur")) ;;`,
    ),
    "  esac",
    "}",
    "",
    `${pathsVariable}=${sq(
      model.commands
        .map((command) => command.id)
        .filter(Boolean)
        .join(" "),
    )}`,
    // `-o default` gives path completion whenever COMPREPLY comes back empty,
    // which is exactly the file/directory and free-text cases above.
    `complete -o default -F _${model.binary.replace(/-/g, "_")}_completions ${model.binary}`,
    "",
  );
  return lines.join("\n");
}

function zsh(model: CompletionModel): string {
  const fn = `_${model.binary.replace(/-/g, "_")}`;
  const lines = [
    `#compdef ${model.binary}`,
    header(model, "#"),
    "",
    `${fn}() {`,
    "  local command_path=''",
    "  local index=2",
    "  local word state",
    "  while (( index < CURRENT )); do",
    '    word="${words[index]}"',
    '    [[ "$word" == -* ]] && break',
    `    if (( \${+_${model.binary.replace(/-/g, "_")}_paths[\${command_path:+$command_path }$word]} )); then`,
    '      command_path="${command_path:+$command_path }$word"',
    "    else",
    "      break",
    "    fi",
    "    (( index++ ))",
    "  done",
    "",
    '  case "$command_path" in',
  ];
  for (const command of model.commands) {
    const specs: string[] = [];
    for (const option of command.options) {
      const description = zshDescription(oneLine(option.description));
      const names = option.short ? `{${option.short},${option.long}}` : option.long;
      // A repeatable option keeps being offered; `*` is zsh's marker for that.
      const prefix = option.repeatable ? "*" : "";
      if (!option.takesValue) {
        specs.push(sq(`${prefix}${names}[${description}]`));
        continue;
      }
      const action =
        option.value === "choice"
          ? `:value:(${option.choices.join(" ")})`
          : option.value === "directory"
            ? ":dir:_files -/"
            : option.value === "file"
              ? ":file:_files"
              : ":value:";
      specs.push(sq(`${prefix}${names}[${description}]${action}`));
    }
    if (command.subcommands.length) {
      // `_describe` over a local array, rather than an inline `((a:b c:d))`
      // value list: each entry is quoted on its own line, so a description
      // containing a quote or a colon cannot break the enclosing spec.
      lines.push(
        `    ${sq(command.id)})`,
        "      local -a _subcommands",
        "      _subcommands=(",
        ...command.subcommands.map((id) => {
          const child = model.commands.find((item) => item.id === id);
          return `        ${sq(`${id.split(" ").pop()!}:${zshDescription(oneLine(child?.description ?? ""))}`)}`;
        }),
        "      )",
        `      _arguments -C ${[...specs, "'1: :->cmd'", "'*::arg:->args'"].join(" ")}`,
        "      [[ $state == cmd ]] && _describe 'command' _subcommands",
        "      ;;",
      );
      continue;
    }
    if (command.argument.kind === "choice") {
      specs.push(`'1:argument:(${command.argument.choices.join(" ")})'`, "'*:argument:'");
    } else if (command.argument.kind === "directory") {
      specs.push("'*:path:_files -/'");
    } else if (command.argument.kind === "file") {
      specs.push("'*:file:_files'");
    } else if (command.argument.kind === "free") {
      specs.push("'*:argument:'");
    }
    lines.push(`    ${sq(command.id)})`, `      _arguments -C ${specs.join(" ")} ;;`);
  }
  lines.push(
    "  esac",
    "}",
    "",
    `typeset -gA _${model.binary.replace(/-/g, "_")}_paths`,
    ...model.commands
      .map((command) => command.id)
      .filter(Boolean)
      .map((id) => `_${model.binary.replace(/-/g, "_")}_paths[${sq(id)}]=1`),
    "",
    `${fn} "$@"`,
    "",
  );
  return lines.join("\n");
}

function fish(model: CompletionModel): string {
  const binary = model.binary;
  const guard = `__fish_${binary.replace(/-/g, "_")}_at`;
  const lines = [
    header(model, "#"),
    "",
    `function ${guard}`,
    "  set -l parts (commandline -opc)",
    "  set -e parts[1]",
    "  set -l path ''",
    "  for part in $parts",
    "    if string match -qr '^-' -- $part",
    "      break",
    "    end",
    "    set -l candidate (string trim " + '"$path $part")',
    "    if contains -- $candidate $argv[2..-1]",
    "      set path $candidate",
    "    else",
    "      break",
    "    end",
    "  end",
    '  test "$path" = "$argv[1]"',
    "end",
    "",
  ];
  const allPaths = model.commands
    .map((command) => command.id)
    .filter(Boolean)
    .map((id) => sq(id))
    .join(" ");
  const at = (id: string): string => `${guard} ${sq(id)} ${allPaths}`;
  for (const command of model.commands) {
    const condition = `-n ${sq(at(command.id))}`;
    for (const id of command.subcommands) {
      const child = model.commands.find((item) => item.id === id);
      lines.push(
        `complete -c ${binary} ${condition} -f -a ${sq(id.split(" ").pop()!)} -d ${sq(oneLine(child?.description ?? ""))}`,
      );
    }
    if (command.argument.kind === "choice")
      for (const choice of command.argument.choices)
        lines.push(`complete -c ${binary} ${condition} -f -a ${sq(choice)}`);
    for (const option of command.options) {
      const parts = [`complete -c ${binary}`, condition];
      if (option.short) parts.push(`-s ${option.short.replace(/^-/, "")}`);
      parts.push(`-l ${option.long.replace(/^--/, "")}`);
      if (option.takesValue) {
        parts.push("-r");
        if (option.value === "choice") parts.push("-f", `-a ${sq(option.choices.join(" "))}`);
        else if (option.value === "free") parts.push("-f");
      } else parts.push("-f");
      parts.push(`-d ${sq(oneLine(option.description))}`);
      lines.push(parts.join(" "));
    }
  }
  lines.push("");
  return lines.join("\n");
}

function powershell(model: CompletionModel): string {
  const lines = [
    header(model, "#"),
    "",
    `Register-ArgumentCompleter -Native -CommandName ${model.binary} -ScriptBlock {`,
    "  param($wordToComplete, $commandAst, $cursorPosition)",
    "",
    `  $known = @(${model.commands
      .map((c) => c.id)
      .filter(Boolean)
      .map(ps)
      .join(", ")})`,
    "  $parts = $commandAst.CommandElements | Select-Object -Skip 1 | ForEach-Object { $_.ToString() }",
    '  $path = ""',
    "  foreach ($part in $parts) {",
    "    if ($part.StartsWith('-')) { break }",
    '    $candidate = if ($path) { "$path $part" } else { $part }',
    "    if ($known -contains $candidate) { $path = $candidate } else { break }",
    "  }",
    "",
    "  $completions = switch ($path) {",
  ];
  for (const command of model.commands) {
    const entries: string[] = [];
    for (const id of command.subcommands) {
      const child = model.commands.find((item) => item.id === id);
      const name = id.split(" ").pop()!;
      entries.push(
        `[System.Management.Automation.CompletionResult]::new(${ps(name)}, ${ps(name)}, 'Command', ${ps(oneLine(child?.description ?? name))})`,
      );
    }
    for (const choice of command.argument.choices)
      entries.push(
        `[System.Management.Automation.CompletionResult]::new(${ps(choice)}, ${ps(choice)}, 'ParameterValue', ${ps(choice)})`,
      );
    for (const option of command.options)
      entries.push(
        `[System.Management.Automation.CompletionResult]::new(${ps(option.long)}, ${ps(option.long)}, 'ParameterName', ${ps(oneLine(option.description) || option.long)})`,
      );
    lines.push(`    ${ps(command.id)} { @(${entries.join(", ")}) }`);
  }
  lines.push(
    "    default { @() }",
    "  }",
    "",
    '  $completions | Where-Object { $_.CompletionText -like "$wordToComplete*" }',
    "}",
    "",
  );
  return lines.join("\n");
}

const GENERATORS: Record<Shell, (model: CompletionModel) => string> = {
  bash,
  zsh,
  fish,
  powershell,
};

export function generateCompletion(model: CompletionModel, shell: Shell): string {
  return GENERATORS[shell](model);
}
